Bench: 1236481

diff --git a/src/Makefile b/src/Makefile
--- a/src/Makefile
+++ b/src/Makefile
@@ -3,8 +3,8 @@ LLVM_PROFDATA := llvm-profdata
 BUILD_DIR := ../build
 BINARY_DIR := ../bin
 
-NETWORK = 4ed21ecb.nn
-EVALFILE := ../network/$(NETWORK)
+EVALURL = https://github.com/KierenP/Halogen-Networks/releases/download/4ed21ecb/4ed21ecb.nn
+EVALFILE = $(BUILD_DIR)/4ed21ecb.nn
 
 SRCS := \
 	BoardState.cpp \
@@ -248,10 +248,16 @@ release:
 $(EVALFILE):
 	@ mkdir -p $(dir $@)
 	@echo "net: $(EVALFILE)"
+	$(eval curl_or_wget := $(shell if hash curl 2>/dev/null; then echo "curl -skL"; elif hash wget 2>/dev/null; then echo "wget -qO-"; fi))
 	@if test -f "$(EVALFILE)"; then \
         echo "Already available."; \
 	else \
-		git lfs pull --include "$(NETWORK)"; \
+		if [ "x$(curl_or_wget)" = "x" ]; then \
+			echo "Automatic download failed: neither curl nor wget is installed. Install one of these tools or download the net manually"; exit 1; \
+		else \
+			echo "Downloading... $(EVALURL)"; $(curl_or_wget) $(EVALURL) > $(EVALFILE);\
+			echo "Download complete."; \
+		fi; \
 	fi;
 
 #----------------------------------------------------------------------------------------------------------------------
