Update main.yml

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -25,11 +25,55 @@ jobs:
           cd src
           make sanitize
           
-      - name: Run builds
+      - name: Address sanitizer
         run: |
-          cd Halogen
-          cd src
-          ./Halogen_undefined.exe bench 8
-          ./Halogen_address.exe bench 8
+          ./Halogen/src/Halogen_address.exe bench 8 2>&1 | grep -A50 "AddressSanitizer:"
+          if test $? == 0
+          then
+              echo "Bench test failed"
+              exit 1
+          fi
+
+          cat << EOF > game.exp
+          set timeout 240
+          spawn ./Halogen/src/Halogen_address.exe
+
+          send "uci\n"
+          expect "uciok"
+
+          send "ucinewgame\n"
+          send "position startpos\n"
+          send "isready\n"
+          expect "readyok"
+          send "go movetime 10000\n"
+          expect "bestmove"
+
+          send "position startpos moves e2e4 e7e6\n"
+          send "isready\n"
+          expect "readyok"
+          send "go movetime 10000\n"
+          expect "bestmove"
+
+          send "ucinewgame"
+          send "isready\n"
+          expect "readyok"
+          send "position fen 5rk1/1K4p1/8/8/3B4/8/8/8 b - - 0 1\n"
+          send "isready\n"
+          expect "readyok"
+          send "go depth 20\n"
+          expect "bestmove"
+
+          send "quit\n"
+          expect eof
+          EOF
+
+          expect game.exp 2>&1 | grep -A50 "AddressSanitizer:"
+          if test $? == 0
+          then
+              echo "Game test failed"
+              exit 1
+          fi
+
+          rm game.exp
 
 
